### ISSUE TITLE
Things left 

### ISSUE THREAD

**Issue by ramyak-mehra** [andriwsluna/upper#14]
What are the things left on the server side to make it ready for production use, except documentation and dart docs. Are there any features left?

**Comment by andriwsluna** [comment]
@ramyak-mehra thanks for your question.
Just one feature that I intend to implement soon, custom services. But to become stable, maturation is necessary. And it just comes with use. After finishing the Client part my company will make a medium-sized application and this will help in the maturation of the framework, however the good thing would be if more people used and opened issues.

**Comment by ramyak-mehra** [comment]
Just tried with an existing database that was created using Django. I noticed I had a datetime field which was converted to string.
shouldn't something like a timestamp be used?
Otherwise looks promising with the little time I spent with this.

**Comment by andriwsluna** [comment]
The proto3 language does not have a native datetime type. There are types that can be imported but converting strings with the format "yyyy-MM-dd hh: nn: ss" appeared to be less complex.
